Feat. ActivityDomain Create
PoolC/poolc-renewal-back pull request #16
Opened 2021-01-25 15:04 UTC by hcpak

### 📕 Issue Number

Close #6

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] Activity, ActivityMember, ActivityTag, Attendance, Session, Tag에 해당하는 domain 추가

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [ ] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?
      <br/>

### 📝 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

cascade에 관련해서 testcase 코드를 작성 후 문제가 확인되면 추가로 고치겠습니다.

<br/><br/>

2021-01-25 15:05 UTC, hcpak commented
<img width="315" alt="스크린샷 2021-01-26 오전 12 04 49" src="https://user-images.githubusercontent.com/68177113/105723427-1cd7aa00-5f6a-11eb-8b1b-5529282d6744.png">
<img width="291" alt="스크린샷 2021-01-26 오전 12 04 56" src="https://user-images.githubusercontent.com/68177113/105723442-2103c780-5f6a-11eb-9980-078df1fe7b29.png">
<img width="252" alt="스크린샷 2021-01-26 오전 12 05 04" src="https://user-images.githubusercontent.com/68177113/105723459-25c87b80-5f6a-11eb-9a76-661803f0f55e.png">
<img width="287" alt="스크린샷 2021-01-26 오전 12 05 12" src="https://user-images.githubusercontent.com/68177113/105723469-2a8d2f80-5f6a-11eb-8188-8fd543025875.png">
<img width="331" alt="스크린샷 2021-01-26 오전 12 05 26" src="https://user-images.githubusercontent.com/68177113/105723502-324cd400-5f6a-11eb-96bb-b9b01417948e.png">
<img width="269" alt="스크린샷 2021-01-26 오전 12 05 35" src="https://user-images.githubusercontent.com/68177113/105723514-3842b500-5f6a-11eb-86e1-7e238027ab87.png">

2021-01-27 02:03 UTC, mingd1023 approved these changes
수고하셨습니다 ~ 다만 커밋은 파일 단위로 나눠서 하는 게 좋았을 것 같아요!

2021-01-27 02:04 UTC, mingd1023 commented
> <img alt="스크린샷 2021-01-26 오전 12 05 04" width="252" src="https://user-images.githubusercontent.com/68177113/105723459-25c87b80-5f6a-11eb-9a76-661803f0f55e.png">

보면 activityid 라고 attribute 이름이 지어지는데 activity_id로 만드는 게 더 나을 것 같네요! activityid 외에 다른 경우도 마찬가지고요,, 이건 토요일에 만나서 얘기해봐요!

2021-01-27 02:56 UTC, hcpak commented
> > <img alt="스크린샷 2021-01-26 오전 12 05 04" width="252" src="https://user-images.githubusercontent.com/68177113/105723459-25c87b80-5f6a-11eb-9a76-661803f0f55e.png">
> 
> 보면 activityid 라고 attribute 이름이 지어지는데 activity_id로 만드는 게 더 나을 것 같네요! activityid 외에 다른 경우도 마찬가지고요,, 이건 토요일에 만나서 얘기해봐요!

넵 이거 저번에 @yoonseokch 이 말한 대로 db에 카멜 케이스로 들어갈 수 있도록 application.yml을 수정해야할 거 같습니다.

2021-01-27 02:56 UTC, hcpak commented
> 수고하셨습니다 ~ 다만 커밋은 파일 단위로 나눠서 하는 게 좋았을 것 같아요!

앞으로는 그렇게 하도록 하겠습니다.

2021-01-27 03:02 UTC, yoonseokch requested changes

2021-01-27 05:22 UTC, merged