feat(jwtTokenProvider) : jwt token 관련 기능 추가 및 버그 수정
PoolC/poolc-renewal-back pull request #68
Opened 2021-02-13 12:01 UTC by yoonseokch

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] validateToken method 추가
- [x] getUserInfo method 추가
- [x] 디버깅용으로 넣어둔 secretkey, expireTimeInMS 값 삭제
- [x] createToken method 수정

### 📘 작업 유형

- [x] 신규 기능 추가
- [x] 버그 수정
- [x] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [x] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?
      <br/>

### 📝 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- jwt 토큰을 decode 하여 올바른 토큰인지, 기간이 만료되지 않은 토큰인지 확인하는 validateToken를 추가하였습니다
- 현재 저희가 token 안의 두가지의 정보를 담는데 그 두가지의 정보를 hashmap으로 반환하는 userInfo Method를 추가하였습니다.
- 기존에 있던 createToken method에서 setClaim를 하면 앞에 있던 기존 정보들이 지워집니다. (issuer,issuedAt,expirationTime). 따라서 setClaim 대신 claim을 사용하여 여러가지 정보들이 claim 안에 담기도록 변경하였습니다.

<br/><br/>

2021-02-13 13:03 UTC, Jjungs7 commented
> ### 📙 작업 내역
> > 구현 내용 및 작업 했던 내역
> 
> * [x]  validateToken method 추가
> * [x]  getUserInfo method 추가
> * [x]  디버깅용으로 넣어둔 secretkey, expireTimeInMS 값 삭제
> * [x]  createToken method 수정

- 브렌치 이름은 보통 camelCase가 아닌, hyphen separated으로 명명합니다(JwtTokenProviderFix -> jwt-token-provider-fix)
  - fix 폴더로 만드는 것은 어떤가요? 물론 실제 폴더는 아니고 gui 툴을 사용하면 폴더처럼 보여줄 뿐입니다 (JwtTokenProviderFix -> fix/jwt-token-provider)
- 커밋과는 별개로 너무 템플릿에 안 따라도 될 것 같아요. 대괄호 안에 x 치는 것도 생각보다 시간이 좀 드는 것 같아요
```text
as-is: [x] validateToken method 추가
to-be: - validateToken method 추가
```
- 작업 내역은 코드를 그대로 옮겨적기보단 사람이 읽기 편한 언어로 + 추상화해주면 더 이해하기 편할 것 같아요
어차피 리뷰할 때 코드를 봐야하는데, *validateToken method 추가* 라는 내용보단 *토큰이 유효한지 확인하는 기능 추가*로 pr 을 날리면 코드를 확인할 때 *validateToken*이 해당 기능이겠구나~ 하고 충분히 유추할 수 있을 것 같아요. (그렇기 때문에 커밋을 기능 단위로, 커밋과 연관된 내용만 포함시키는 것이 바람직하겠죠? 물론 저도 잘 지키진 않습니다 😂)
```text
as-is: [x] validateToken method 추가
to-be: - 토큰이 유효한지 확인하는 기능 추가
```

2021-02-14 03:48 UTC, yoonseokch commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
> +    }
value object를 사용할 생각을 못하고 있었네요 참조해서 수정하도록 하겠습니다

2021-02-14 03:57 UTC, yoonseokch commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
> +    }
exception 종류를 살펴보지않고 참조한 사이트에서 따로 체크해주길래 잡아주지 않는줄 알았습니다. 맞춰서 수정하겠습니다 ParsedTokenValues는 아까 말씀하신 vo인가요??

2021-02-14 04:40 UTC, Jjungs7 commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
> +    }
네 더 좋은 이름이 떠오르면 바꿔도 괜찮을 것 같아요.

> UserInfo 하면 Member 정보를 조회하는건가? 라고 혼동할 수 있을 것 같아요. 다른 이름을 써보는 것은 어떨까요?
위 리뷰에 대한 연장선으로, JwtTokenProvider는 Jwts 라이브러리 wrapper 클래스인데 해당 클래스에서 멤버 정보 조회를 직접 하는게 맞을까 생각해보시면 좋을 것 같습니다. 저는 상세 정보 조회를 ParsedTokenValues VO에게 위임하는 방식으로 구현할 것 같은데, 본인은 어떻게 구현할지 생각해보세요. (Claims 클래스를 살펴보면 Map을 상속받네요. 그럼 entrySet 또는 keySet을 활용해서 본인만의 Map을 만들 수 있지 않을까요?)

2021-02-15 06:14 UTC, yoonseokch commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
> +    }
아하 jwtTokenProvider는 claim을 가져오는 역할까지만 하고 vo에서 생성자로 상세정보를 뽑아오자는 말씀이신가요??

2021-02-15 07:43 UTC, hcpak commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
> +                .claim("isAdmin", member.getIsAdmin().toString())
저는 다음과 같이 했는데
```
.claim("isAdmin", member.getIsAdmin())
```
member.getIsAdmin()을 toString()으로 바꾸는 이유가 있나요? 

member.getIsAdmin()을 string으로 바꾸게 된다면, MemberService에서 임원인지 아닌지 판별할 때 String의 equal() 메소드로 비교해야 해서 Boolean으로 처리하는 게 좋다고 생각합니다.

MemberAcceptanceTest에서 비허가 회원이 있다고 가정하는 테스트가 있는데, 비허가 회원임을 판별하려면 isActivated 정보도 들어가야 할거 같습니다.

2021-02-15 07:43 UTC, hcpak commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
>                  .compact();
저 같은 경우에는 Header에 토큰 타입과 해쉬 알고리즘을 추가해야 한다는 글(https://galid1.tistory.com/581)을 통해 다음과 같이 코드를 짰습니다.
```
        Map<String, Object> headers = new HashMap<>();
        headers.put("typ", "JWT");
        headers.put("alg", "HS256");

        Date now = new Date(), expiredTime = new Date();
        expiredTime.setTime(now.getTime() + expireTimeInMS);

        Map<String, Object> payloads = new HashMap<>();
        payloads.put("iss", "PoolC/PROJECT_NAME_HERE");
        payloads.put("iat", now);
        payloads.put("exp", expiredTime);
        payloads.put("id", member.getUUID());
        payloads.put("isAdmin", member.getIsAdmin());
        payloads.put("isActivated", member.getIsActivated());

        return Jwts.builder()
                .setHeader(headers)
                .setClaims(payloads)
                .signWith(SignatureAlgorithm.HS256, secretKey)
                .compact();
```

2021-02-15 11:35 UTC, yoonseokch commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
>                  .compact();
뒤에있는 signWith(SignatureAlgorithm.HS256, secretKey)에 이미 해당 내용이 들어가지 않나요?

2021-02-15 11:37 UTC, yoonseokch commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
> +                .claim("isAdmin", member.getIsAdmin().toString())
toString으로 하는건 내일 같이 해봅시다. 그리고 사실 비허가회원이 로그인을 못하지 않나요..? 내일 같이 auth 를 확인해봅시다

2021-02-16 03:26 UTC, Jjungs7 commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
> +    }
네 맞습니다

2021-02-16 03:30 UTC, Jjungs7 commented on src/main/java/org/poolc/api/auth/infra/JwtTokenProvider.java
>                  .compact();
payload에 모든 정보를 넣기보단 setExpiration과 같은 메서드로 선언하는 것이 낫다고 봅니다. uuid, admin과 같은 정보는 payload에 넣어서 setClaims 하는 방법은 괜찮은 것 같아요

2021-02-16 08:58 UTC, Jjungs7 requested changes

2021-02-16 08:58 UTC, Jjungs7 commented on src/test/java/org/poolc/api/member/MemberAcceptanceTest.java
> +        ExtractableResponse<Response> response = deleteMemberRequest(accessToken, list.get(0).getUuid());
```suggestion
                ExtractableResponse<Response> membersResponse = getMembersRequest(accessToken);
        List<MemberResponse> members = membersResponse.body().jsonPath().getList(".", MemberResponse.class);

        ExtractableResponse<Response> response = deleteMemberRequest(accessToken, members.get(0).getUuid());
```

요렇게 바꿀 수 있겠네요. 그러면 Gson 의존성 제거도 가능하겠네요 (시간나면 의존성 낮출수록 이득인 이유를 생각해보고 찾아봐도 좋을 것 같아요)

2021-02-16 08:58 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/controller/MemberController.java
> +    public ResponseEntity deleteMember(HttpServletRequest request, @Param("UUID") String UUID) {
typed 언어의 장점을 최대한 활용해봅시다. 아래와 같은 오류를 컴파일러 단계에서 잡을 수 있겠네요!
참고로 Member를 지웠는데 MemberResponse를 응답하면 안 되겠죠? 이 상황에서 더 적절한 자료형이 있을까요?

![Screen Shot 2021-02-16 at 5 55 12 PM](https://user-images.githubusercontent.com/14287915/108040026-268f9180-7080-11eb-8ed5-fdf1bbe8ad0e.png)

2021-02-16 09:01 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/controller/MemberController.java
> +            throw new UnauthenticatedException("임원진이 아닙니다");
코드상에서 여기까지 온걸 보니 인증된 회원이겠네요. 그럼 unauthenticated(인증)일까요 아니면 unauthorized(인가) 일까요? (관련해서 401, 403 에러 코드도 같이 살펴보면 좋아요). 이번 프로젝트에 반영하라고 하진 않을게요

2021-02-16 15:40 UTC, Jjungs7 commented on src/main/java/org/poolc/api/auth/service/AuthService.java
> +        }
여기에 이 로직이 왜 필요한지 한참을 생각했는데, 물론 인증되지 않은 것은 맞지만 풀씨에서 자체적으로 정한 허가되지 않은(비활성화) 회원과 단순히 id pw 를 틀려서 인증되지 않은 사람 두 경우 모두에 unauthenticated 용어를 쓰게 되네요. 혼동을 줄이기 위해 두 케이스 모두 나누는 것은 어떤가요?

2021-02-16 15:58 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/controller/MemberController.java
> +    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
private 또는 protected으로 선언된 메소드들을 되도록이면 가장 아래로 옮겨주세요

---

클린코드 중에서 이런 비슷한 내용이 있습니다
- 객체의 인터페이스는 최상단에 위치하고 이외에 객체 내부에서 수행하는 일들은 최대한 캡슐화하라

인터페이스는 뭘까요? 이 객체와 상호작용할 수 있는 유일한 통로입니다. 파일을 읽기 시작했을때 인터페이스부터 모두 보였으면 좋겠습니다.

2021-02-16 16:22 UTC, Jjungs7 requested changes

2021-02-16 16:22 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/infra/BearerAuthInterceptor.java
> +    }
👍 의도를 드러내는 메소드 좋습니다

- 현재 메소드가 protected으로 오픈되어있는데 특별한 이유가 없으면 private으로 해주세요
- 토큰 종류에는 Basic, Bearer 등등이 있습니다. 이왕이면 Bearer 토큰인지 확실히 하는게 좋지 않을까요?
  - 동시에 removeBearerFromToken 이라는 이름보다는 더 적절한 이름이 있을지 같이 고민해보는 것도 좋겠네요

2021-02-16 16:22 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/infra/WebMvcConfig.java
> +
생성자가 하나면 @Autowired 가 자동으로 붙기는 하나, 명시적으로 적어주는 것을 권장합니다

2021-02-16 16:22 UTC, Jjungs7 commented on src/test/java/org/poolc/api/member/MemberAcceptanceTest.java
> +
- [여기](https://github.com/PoolC/poolc-renewal-back/pull/68/commits/0c9852166e4d7d2b56d59db8078f22213f07587e#diff-6ca9bf6a6913daee5f49fe587ca01f12f73f7e2956ea22ffa743735b237e0d37R9)와 memberResponse 변수 부분.. 깐깐해서 죄송한데 커밋할때 인텔리제이로 무슨 내용이 커밋되는지 보이니까 꼭 확인하고 필요하지 않은 부분은 제외해주셨으면 좋겠어요
- 두 줄을 띄운 이유가 있을까요? 한 줄로 구분하는 것은 가독성을 높이지만 두 줄 부터는 떨어지는 것 같습니다

---

인수테스트는 정말 "기능만" 잘 작동하는지 확인하는 것이 아닌, 유저가 실제로 상호작용한다는 생각으로 작성해주셨으면 해요. 시나리오를 쓴다고 생각하면 좋을 것 같아요.
- 위의 경우에는 (쓰지 않고 있는 memberResponse 변수를 무시한다면) 임원진이 로그인하고 스트링 내용으로 보아 이미 삭제된 멤버를 삭제하려고 하네요. 이미 삭제된 멤버를 또 삭제하려고 하는데 OK인 것이 조금 이상한 것 같네요
- 이제 DELETED_MEMBER_ID가 우리가 지우고 싶은 회원이라고 가정할게요. 실제로 서비스를 사용한다고 생각해봤을때, 임원진이 뜬금없이 회원의 정보를 삭제할 것이라고 생각하지 않습니다. 이 서비스를 사용하는 유저 입장에서 봤을때, 회원정보를 삭제하는 경우가 무엇이 있을지 고민해보고 그에 맞게 테스트를 작성해보시는게 좋을 것 같아요 (한 두 요청이 추가될 수도 있고 단순히 문자열값만 바뀔 수도 있지만, 관리되지 않는 테스트는 버림받을 확률이 높기 때문에 테스트 작성 \***의도**\*를 명확히 드러내는게 중요합니다)

2021-02-16 16:26 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/repository/MemberRepository.java
> +    Optional<Member> findByLoginID(String loginID);
제가 놓친 부분이 있었네요 👍

2021-02-16 16:31 UTC, Jjungs7 requested changes

2021-02-16 16:31 UTC, Jjungs7 commented on src/test/java/org/poolc/api/member/MemberAcceptanceTest.java
>          assertThat(response.statusCode()).isEqualTo(HttpStatus.NO_CONTENT.value());
이거 제가 작성했네요? 😂

존재하지 않는 회원을 삭제하려고 하는거니까 괜찮다의 의미를 내포하는 2XX 상태코드보단 4XX (아마도 Bad request가 제일 맞을 것 같은데) 류의 상태코드를 기대하는게 더 맞을 것 같아요. 너무 예시코드를 맹신하진 말아주세요....

2021-02-16 16:31 UTC, Jjungs7 commented on src/test/java/org/poolc/api/member/MemberAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.FORBIDDEN.value());
forbidden status code는 인증은 되었지만 인가되지 않은 경우에 사용됩니다
예를 들어 일반 회원이 관리자 권한으로 회원을 삭제하려고 할때 이에 해당할 수 있겠습니다

여기서는 입력이 틀렸으니 bad request는 어떠신가요?

2021-02-16 16:40 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/infra/BearerAuthInterceptor.java
> +    public boolean preHandle(HttpServletRequest request,
여담으로 accessToken 은 하루정도로 expirationTime을 짧게 가져갑니다. 유출이 된다고 해도 그 여파가 작게 하기 위함입니다.
현재 구조상으로 expiry time을 하루로 가져가면 하루 지날때마다 새로 로그인해야 할 것 같은데 매우 귀찮을 것 같네요
어떻게 확장할 것인지 고민해보시면 좋겠습니다
참고로 이 파일은 auth package에 있는게 더 맞는 것 같습니다

너무 이것에만 시간을 쏟으면 지칠 수 있으니 다른 기능 모두 완성한 후에 생각해봐도 좋을 것 같습니다 (하지만 미구현된 상태로 출시하기엔 사용하는 입장에서 너무 불편할 것 같아요)

2021-02-16 23:49 UTC, Jjungs7 requested changes

2021-02-16 23:54 UTC, Jjungs7 commented on src/test/java/org/poolc/api/member/MemberAcceptanceTest.java
> +        assertThat(response.statusCode()).isEqualTo(HttpStatus.OK.value());
- [여기](https://github.com/PoolC/poolc-renewal-back/pull/68/commits/0c9852166e4d7d2b56d59db8078f22213f07587e#diff-6ca9bf6a6913daee5f49fe587ca01f12f73f7e2956ea22ffa743735b237e0d37R9)와 memberResponse 변수 부분.. 깐깐해서 죄송한데 커밋할때 인텔리제이로 무슨 내용이 커밋되는지 보이니까 꼭 확인하고 필요하지 않은 부분은 제외해주셨으면 좋겠어요
- 두 줄을 띄운 이유가 있을까요? 한 줄로 구분하는 것은 가독성을 높이지만 두 줄 부터는 떨어지는 것 같습니다
- 메소드는 존재하는 회원을 삭제한다고 하는데 스트링값은 이미 삭제된 회원을 지우려고 하네요 🤔

2021-02-17 05:12 UTC, hcpak commented on src/main/java/org/poolc/api/auth/service/AuthService.java
> +        }
해당 코드는 비허가된 회원은 로그인할 수 없도록 만들기 위해서 다음과 같은 코드를 작성했습니다. 

비활성화된 회원이라서 인증되지 않은 케이스일 때 UnactivatedException으로 만들어서 처리했고, 해당 에러가 존재할 경우 HTTP status Forbidden으로 보내게 했는데 제대로 작성한 건지에 대해 궁금합니다.

2021-02-17 08:42 UTC, hcpak commented on src/main/java/org/poolc/api/member/infra/BearerAuthInterceptor.java
> +        ParsedTokenValues userInfo = jwtTokenProvider.getUserInfo(token);
> 2.내부적으로 토큰 validation을 하지만 메시지만으로는 전혀 의도를 알 수 없어요. 흔히 말하는 side-effect가 이런 곳에서 발생하는 것입니다. (이 메소드를 처음 쓰는 사람: null을 리턴하거나 그냥 무시할 것 같은데 계속 throw가 일어나네?)

여기에서  메시지라는 게 무엇인지 잘 모르겠는데, 여기서 말하는 메시지가 혹시 이부분을 말씀하시는 건가요? 
```
ParsedTokenValues userInfo = getUserInfo(request);
request.setAttribute("UUID", userInfo.getUUID());
request.setAttribute("isAdmin", userInfo.getIsAdmin());
```
그리고 2번에 대해서 추상적으로 느껴져서 상황이 이해가 잘 가지 않습니다.

2021-02-17 14:12 UTC, Jjungs7 requested changes

2021-02-17 14:12 UTC, Jjungs7 commented on src/main/java/org/poolc/api/member/service/MemberService.java
> +                .get();
이 형태를 자바의 함수형 프로그래밍이라고 하는데, 이런 if 문을 줄이고자 도입되었습니다(if, for, while은 indentation이 늘어나고 분기를 생각하게 만드니까요). if 없이 작성해보아요

2021-02-17 14:12 UTC, Jjungs7 commented on src/test/java/org/poolc/api/member/MemberAcceptanceTest.java
>          // 임원진이 요청 보낸다고 가정
이건 dataloader를 만들때 참고하라고 넣은 주석이라 지워도 될 것 같아요. 마찬가지로 todo도 구현했으면 지워주는게 좋을 것 같습니다

2021-02-17 14:12 UTC, Jjungs7 commented on src/test/java/org/poolc/api/member/MemberAcceptanceTest.java
>          assertThat(response.statusCode()).isEqualTo(HttpStatus.UNAUTHORIZED.value());
ㅎㅎㅎ 여기도 제가 작성했는데 인증과 인가의 차이를 알았으니 알맞게 바꿔볼까요?
참고로
인증실패 - HTTPStatus.UNAUTHORIZED
인가되지 않음 - HTTPStatus.FORBIDDEN
과 매칭됩니다(인증은 authentication인데도 불구하고 http status는 unauthorized인게 헷갈리긴 합니다)

2021-02-18 01:46 UTC, merged